import { Product } from "@/types/product";

// Mock Ürün Verileri
export const PRODUCTS: Product[] = [
  // Fındık Ezmeleri
  {
    id: "findik-sekersiz",
    name: "Şekersiz Fındık Ezmesi",
    slug: "sekersiz-findik-ezmesi",
    description:
      "Giresun kalitesi fıstıklardan üretilen, katkısız ve şekersiz fındık ezmesi. Hiçbir ilave şeker içermeyen bu ürün, fıstığın doğal tatlılığını korur.",
    shortDescription:
      "İçeriğinde sadece fıstık bulunan %100 doğal fındık ezmesi. Rafine şeker ve katkı maddesi içermez.",
    category: "findik",
    subcategory: "sekersiz",
    images: [
      "/images/products/sekersiz-findik-1.jpg",
      "/images/products/sekersiz-findik-2.jpg",
    ],
    tags: ["doğal", "sekersiz", "vegan", "glutensiz"],
    variants: [
      {
        id: "findik-sekersiz-250",
        name: "250g",
        weight: 250,
        price: 239,
        stock: 50,
        sku: "EZM-FS-250",
      },
      {
        id: "findik-sekersiz-450",
        name: "450g",
        weight: 450,
        price: 429,
        stock: 35,
        sku: "EZM-FS-450",
      },
      {
        id: "findik-sekersiz-850",
        name: "850g",
        weight: 850,
        price: 649,
        stock: 20,
        sku: "EZM-FS-850",
      },
    ],
    nutritionalInfo: {
      calories: 630,
      protein: 15,
      carbs: 12,
      fat: 55,
      fiber: 8,
    },
    vegan: true,
    glutenFree: true,
    sugarFree: true,
    highProtein: true,
    rating: 5,
    reviewCount: 210,
    featured: true,
    new: false,
  },
  {
    id: "findik-balli",
    name: "Ballı Fındık Ezmesi",
    slug: "balli-findik-ezmesi",
    description:
      "Giresun kalitesi fıstıklarla balın mükemmel uyumu. Doğal arı balı eklenerek tatlandırılmış, katkısız bir lezzet.",
    shortDescription:
      "Fındık ezmesine doğal arı balı eklenerek hazırlanmış, enerji veren doğal besin.",
    category: "findik",
    subcategory: "balli",
    images: ["/images/products/balli-findik-1.jpg", "/images/products/balli-findik-2.jpg"],
    tags: ["doğal", "balli", "vegan", "glutensiz", "enerji"],
    variants: [
      { id: "findik-balli-250", name: "250g", weight: 250, price: 249, stock: 45, sku: "EZM-FB-250" },
      { id: "findik-balli-450", name: "450g", weight: 450, price: 449, stock: 30, sku: "EZM-FB-450" },
      { id: "findik-balli-850", name: "850g", weight: 850, price: 699, stock: 15, sku: "EZM-FB-850" },
    ],
    nutritionalInfo: { calories: 580, protein: 14, carbs: 28, fat: 48, fiber: 7, sugar: 15 },
    vegan: true,
    glutenFree: true,
    sugarFree: false,
    highProtein: true,
    rating: 5,
    reviewCount: 227,
    featured: true,
    new: false,
  },
  {
    id: "findik-hurmali",
    name: "Hurmalı Fındık Ezmesi",
    slug: "hurmali-findik-ezmesi",
    description:
      "Fındık ezmesi ile doğal hurmunun birleşimi. Rafine şeker yerine hurma kullanılarak tatlandırılmış sağlıklı bir alternatif.",
    shortDescription:
      "Fındık ezmesine doğal hurma eklenerek hazırlanmış, şekersiz ve besleyici bir lezzet.",
    category: "findik",
    subcategory: "hurmali",
    images: ["/images/products/hurmali-findik-1.jpg", "/images/products/hurmali-findik-2.jpg"],
    tags: ["doğal", "hurmali", "vegan", "glutensiz"],
    variants: [
      {
        id: "findik-hurmali-250",
        name: "250g",
        weight: 250,
        price: 249,
        stock: 40,
        sku: "EZM-FH-250",
      },
      {
        id: "findik-hurmali-450",
        name: "450g",
        weight: 450,
        price: 449,
        stock: 25,
        sku: "EZM-FH-450",
      },
      {
        id: "findik-hurmali-850",
        name: "850g",
        weight: 850,
        price: 699,
        stock: 12,
        sku: "EZM-FH-850",
      },
    ],
    nutritionalInfo: { calories: 560, protein: 13, carbs: 32, fat: 46, fiber: 9, sugar: 18 },
    vegan: true,
    glutenFree: true,
    sugarFree: false,
    highProtein: true,
    rating: 5,
    reviewCount: 180,
    featured: true,
    new: false,
  },
  {
    id: "findik-kakaolu",
    name: "Kakaolu Fındık Ezmesi",
    slug: "kakaolu-findik-ezmesi",
    description:
      "Fındık ezmesi ile doğal kakaoning mükemmel uyumu. Çikolata severler için sağlıklı bir alternatif.",
    shortDescription:
      "Fındık ezmesine doğal kakao eklenerek hazırlanmış, çikolata tadında bir lezzet.",
    category: "findik",
    subcategory: "kakaolu",
    images: ["/images/products/kakaolu-findik-1.jpg", "/images/products/kakaolu-findik-2.jpg"],
    tags: ["doğal", "kakaolu", "vegan", "glutensiz", "cikolata"],
    variants: [
      {
        id: "findik-kakaolu-250",
        name: "250g",
        weight: 250,
        price: 229,
        stock: 38,
        sku: "EZM-FK-250",
      },
      {
        id: "findik-kakaolu-450",
        name: "450g",
        weight: 450,
        price: 419,
        stock: 22,
        sku: "EZM-FK-450",
      },
      {
        id: "findik-kakaolu-850",
        name: "850g",
        weight: 850,
        price: 649,
        stock: 10,
        sku: "EZM-FK-850",
      },
    ],
    nutritionalInfo: { calories: 550, protein: 12, carbs: 35, fat: 42, fiber: 10, sugar: 12 },
    vegan: true,
    glutenFree: true,
    sugarFree: false,
    highProtein: false,
    rating: 5,
    reviewCount: 91,
    featured: false,
    new: false,
  },
  {
    id: "findik-sutlu-krema",
    name: "Sütlü Fındık Kreması",
    slug: "sutlu-findik-kremasi",
    description:
      "Fındık kremanın yumuşacık tadı. Kahvaltıların vazgeçilmezi, çocukların favorisi.",
    shortDescription:
      "Fındık kremasına süt eklenerek hazırlanmış, yumuşak kıvamlı bir lezzet.",
    category: "findik",
    subcategory: "sutlu-findik-kremasi",
    images: ["/images/products/sutlu-findik-1.jpg", "/images/products/sutlu-findik-2.jpg"],
    tags: ["sutlu", "kahvalti", "cocuklar"],
    variants: [
      {
        id: "findik-sutlu-250",
        name: "250g",
        weight: 250,
        price: 160,
        stock: 42,
        sku: "EZM-FSK-250",
      },
      {
        id: "findik-sutlu-450",
        name: "450g",
        weight: 450,
        price: 280,
        stock: 28,
        sku: "EZM-FSK-450",
      },
      {
        id: "findik-sutlu-850",
        name: "850g",
        weight: 850,
        price: 440,
        stock: 18,
        sku: "EZM-FSK-850",
      },
    ],
    nutritionalInfo: { calories: 480, protein: 10, carbs: 42, fat: 32, fiber: 5, sugar: 22 },
    vegan: false,
    glutenFree: true,
    sugarFree: false,
    highProtein: false,
    rating: 5,
    reviewCount: 88,
    featured: true,
    new: false,
  },
  {
    id: "findik-klasik",
    name: "Klasik Fındık Ezmesi",
    slug: "klasik-findik-ezmesi",
    description:
      "Geleneksel tariflerle hazırlanan klasik fındık ezmesi. Kahvaltıların, tatlıların ve içeceklerin tamamlayıcısı.",
    shortDescription:
      "Klasik usul fındık ezmesi. Akışkan kıvamı ve yoğun fındık tadıyla.",
    category: "findik",
    subcategory: "klasik",
    images: ["/images/products/klasik-findik-1.jpg", "/images/products/klasik-findik-2.jpg"],
    tags: ["klasik", "geleneksel", "kahvalti"],
    variants: [
      {
        id: "findik-klasik-250",
        name: "250g",
        weight: 250,
        price: 239,
        stock: 48,
        sku: "EZM-FKLS-250",
      },
      {
        id: "findik-klasik-450",
        name: "450g",
        weight: 450,
        price: 429,
        stock: 32,
        sku: "EZM-FKLS-450",
      },
      {
        id: "findik-klasik-850",
        name: "850g",
        weight: 850,
        price: 679,
        stock: 16,
        sku: "EZM-FKLS-850",
      },
    ],
    nutritionalInfo: { calories: 620, protein: 14, carbs: 14, fat: 54, fiber: 7, sugar: 8 },
    vegan: true,
    glutenFree: true,
    sugarFree: true,
    highProtein: true,
    rating: 5,
    reviewCount: 104,
    featured: false,
    new: false,
  },

  // Fıstık Ezmeleri
  {
    id: "fistik-sekersiz",
    name: "Şekersiz Fıstık Ezmesi",
    slug: "sekersiz-fistik-ezmesi",
    description:
      "Yer fıstığından üretilen, katkısız ve şekersiz fıstık ezmesi. Sporcuların ve diyet yapanların favorisi.",
    shortDescription:
      "İçeriğinde sadece yer fıstığı bulunan %100 doğal fıstık ezmesi.",
    category: "fistik",
    subcategory: "sekersiz",
    images: ["/images/products/sekersiz-fistik-1.jpg", "/images/products/sekersiz-fistik-2.jpg"],
    tags: ["doğal", "sekersiz", "vegan", "glutensiz", "sporcu"],
    variants: [
      {
        id: "fistik-sekersiz-250",
        name: "250g",
        weight: 250,
        price: 189,
        stock: 55,
        sku: "EZM-PIS-250",
      },
      {
        id: "fistik-sekersiz-450",
        name: "450g",
        weight: 450,
        price: 339,
        stock: 38,
        sku: "EZM-PIS-450",
      },
      {
        id: "fistik-sekersiz-850",
        name: "850g",
        weight: 850,
        price: 499,
        stock: 20,
        sku: "EZM-PIS-850",
      },
    ],
    nutritionalInfo: { calories: 580, protein: 25, carbs: 16, fat: 46, fiber: 8 },
    vegan: true,
    glutenFree: true,
    sugarFree: true,
    highProtein: true,
    rating: 5,
    reviewCount: 146,
    featured: true,
    new: false,
  },
  {
    id: "fistik-balli",
    name: "Ballı Fıstık Ezmesi",
    slug: "balli-fistik-ezmesi",
    description:
      "Yer fıstığı ile doğal arı balının birleşimi. Enerji veren, doyurucu bir doğal besin.",
    shortDescription:
      "Fıstık ezmesine doğal arı balı eklenerek hazırlanmış enerji kaynağı.",
    category: "fistik",
    subcategory: "balli",
    images: ["/images/products/balli-fistik-1.jpg", "/images/products/balli-fistik-2.jpg"],
    tags: ["doğal", "balli", "vegan", "glutensiz", "enerji"],
    variants: [
      {
        id: "fistik-balli-250",
        name: "250g",
        weight: 250,
        price: 199,
        stock: 42,
        sku: "EZM-PIB-250",
      },
      {
        id: "fistik-balli-450",
        name: "450g",
        weight: 450,
        price: 349,
        stock: 30,
        sku: "EZM-PIB-450",
      },
      {
        id: "fistik-balli-850",
        name: "850g",
        weight: 850,
        price: 529,
        stock: 18,
        sku: "EZM-PIB-850",
      },
    ],
    nutritionalInfo: { calories: 540, protein: 23, carbs: 28, fat: 40, fiber: 7, sugar: 14 },
    vegan: true,
    glutenFree: true,
    sugarFree: false,
    highProtein: true,
    rating: 5,
    reviewCount: 98,
    featured: false,
    new: false,
  },
  {
    id: "fistik-klasik",
    name: "Klasik Fıstık Ezmesi",
    slug: "klasik-fistik-ezmesi",
    description:
      "Klasik Amerikan tarzı fıstık ezmesi. Tuzsuz, şeker ilavesiz, sadece yer fıstığı.",
    shortDescription: "Klasik usul fıstık ezmesi. Tuzsuz ve şekersiz.",
    category: "fistik",
    subcategory: "klasik",
    images: ["/images/products/klasik-fistik-1.jpg", "/images/products/klasik-fistik-2.jpg"],
    tags: ["klasik", "amerikan", "kahvalti"],
    variants: [
      {
        id: "fistik-klasik-250",
        name: "250g",
        weight: 250,
        price: 189,
        stock: 50,
        sku: "EZM-PIKLS-250",
      },
      {
        id: "fistik-klasik-450",
        name: "450g",
        weight: 450,
        price: 339,
        stock: 35,
        sku: "EZM-PIKLS-450",
      },
      {
        id: "fistik-klasik-850",
        name: "850g",
        weight: 850,
        price: 499,
        stock: 22,
        sku: "EZM-PIKLS-850",
      },
    ],
    nutritionalInfo: { calories: 590, protein: 24, carbs: 16, fat: 48, fiber: 8, sugar: 4 },
    vegan: true,
    glutenFree: true,
    sugarFree: true,
    highProtein: true,
    rating: 5,
    reviewCount: 164,
    featured: true,
    new: false,
  },

  // Antep Fıstığı Ezmeleri
  {
    id: "antep-sekersiz",
    name: "Şekersiz Antep Fıstığı Ezmesi",
    slug: "sekersiz-antep-fistigi-ezmesi",
    description:
      "Gaziantep'in en iyi antep fıstıklarından üretilen, katkısız ve şekersiz ezme. Premium kalite.",
    shortDescription:
      "İçeriğinde sadece Antep fıstığı bulunan %100 doğal, premium kalite ezme.",
    category: "antep-fistigi",
    subcategory: "sekersiz",
    images: ["/images/products/sekersiz-antep-1.jpg", "/images/products/sekersiz-antep-2.jpg"],
    tags: ["premium", "sekersiz", "vegan", "glutensiz", "gaziantep"],
    variants: [
      {
        id: "antep-sekersiz-250",
        name: "250g",
        weight: 250,
        price: 469,
        stock: 30,
        sku: "EZM-PPS-250",
      },
      {
        id: "antep-sekersiz-450",
        name: "450g",
        weight: 450,
        price: 799,
        stock: 25,
        sku: "EZM-PPS-450",
      },
      {
        id: "antep-sekersiz-850",
        name: "850g",
        weight: 850,
        price: 1390,
        stock: 15,
        sku: "EZM-PPS-850",
      },
    ],
    nutritionalInfo: { calories: 610, protein: 22, carbs: 14, fat: 52, fiber: 6 },
    vegan: true,
    glutenFree: true,
    sugarFree: true,
    highProtein: true,
    rating: 5,
    reviewCount: 185,
    featured: true,
    new: false,
  },
  {
    id: "antep-balli",
    name: "Ballı Antep Fıstığı Ezmesi",
    slug: "balli-antep-fistigi-ezmesi",
    description:
      "Antep fıstığı ile doğal arı balının mükemmel uyumu. Tatlı sevenler için premium bir seçim.",
    shortDescription:
      "Antep fıstığı ezmesine doğal arı balı eklenerek hazırlanmış premium lezzet.",
    category: "antep-fistigi",
    subcategory: "balli",
    images: ["/images/products/balli-antep-1.jpg", "/images/products/balli-antep-2.jpg"],
    tags: ["premium", "balli", "vegan", "glutensiz", "gaziantep"],
    variants: [
      {
        id: "antep-balli-250",
        name: "250g",
        weight: 250,
        price: 489,
        stock: 28,
        sku: "EZM-PPB-250",
      },
      {
        id: "antep-balli-450",
        name: "450g",
        weight: 450,
        price: 849,
        stock: 20,
        sku: "EZM-PPB-450",
      },
      {
        id: "antep-balli-850",
        name: "850g",
        weight: 850,
        price: 1449,
        stock: 12,
        sku: "EZM-PPB-850",
      },
    ],
    nutritionalInfo: { calories: 570, protein: 20, carbs: 26, fat: 46, fiber: 5, sugar: 12 },
    vegan: true,
    glutenFree: true,
    sugarFree: false,
    highProtein: true,
    rating: 5,
    reviewCount: 112,
    featured: false,
    new: false,
  },
  {
    id: "antep-klasik",
    name: "Klasik Antep Fıstığı Ezmesi",
    slug: "klasik-antep-fistigi-ezmesi",
    description:
      "Geleneksel Gaziantep usulü antep fıstığı ezmesi. Özel tatlar için özel üretim.",
    shortDescription:
      "Gaziantep'in lezzeti, klasik tariflerle. Konuklarınıza ikram edin.",
    category: "antep-fistigi",
    subcategory: "klasik",
    images: ["/images/products/klasik-antep-1.jpg", "/images/products/klasik-antep-2.jpg"],
    tags: ["premium", "klasik", "gaziantep", "ikram"],
    variants: [
      {
        id: "antep-klasik-250",
        name: "250g",
        weight: 250,
        price: 549,
        stock: 25,
        sku: "EZM-PPKLS-250",
      },
      {
        id: "antep-klasik-450",
        name: "450g",
        weight: 450,
        price: 949,
        stock: 18,
        sku: "EZM-PPKLS-450",
      },
      {
        id: "antep-klasik-850",
        name: "850g",
        weight: 850,
        price: 1549,
        stock: 10,
        sku: "EZM-PPKLS-850",
      },
    ],
    nutritionalInfo: { calories: 600, protein: 21, carbs: 16, fat: 50, fiber: 6, sugar: 6 },
    vegan: true,
    glutenFree: true,
    sugarFree: true,
    highProtein: true,
    rating: 5,
    reviewCount: 106,
    featured: false,
    new: false,
  },

  // Badem Ezmeleri
  {
    id: "badem-sekersiz",
    name: "Şekersiz Badem Ezmesi",
    slug: "sekersiz-badem-ezmesi",
    description:
      "Kaliforniya bademinden üretilen, katkısız ve şekersiz badem ezmesi. Vegan ve keto diyeti için ideal.",
    shortDescription:
      "İçeriğinde sadece badem bulunan %100 doğal badem ezmesi.",
    category: "badem",
    subcategory: "sekersiz",
    images: ["/images/products/sekersiz-badem-1.jpg", "/images/products/sekersiz-badem-2.jpg"],
    tags: ["doğal", "sekersiz", "vegan", "glutensiz", "keto"],
    variants: [
      {
        id: "badem-sekersiz-250",
        name: "250g",
        weight: 250,
        price: 249,
        stock: 45,
        sku: "EZM-AS-250",
      },
      {
        id: "badem-sekersiz-450",
        name: "450g",
        weight: 450,
        price: 449,
        stock: 32,
        sku: "EZM-AS-450",
      },
      {
        id: "badem-sekersiz-850",
        name: "850g",
        weight: 850,
        price: 679,
        stock: 18,
        sku: "EZM-AS-850",
      },
    ],
    nutritionalInfo: { calories: 610, protein: 21, carbs: 14, fat: 53, fiber: 10 },
    vegan: true,
    glutenFree: true,
    sugarFree: true,
    highProtein: true,
    rating: 5,
    reviewCount: 50,
    featured: true,
    new: false,
  },
  {
    id: "badem-balli",
    name: "Ballı Badem Ezmesi",
    slug: "balli-badem-ezmesi",
    description:
      "Badem ezmesi ile doğal arı balının birleşimi. Şekersiz ama tatlı bir lezzet arayanlar için.",
    shortDescription:
      "Badem ezmesine doğal arı balı eklenerek hazırlanmış, şekersiz ama tatlı bir lezzet.",
    category: "badem",
    subcategory: "balli",
    images: ["/images/products/balli-badem-1.jpg", "/images/products/balli-badem-2.jpg"],
    tags: ["doğal", "balli", "vegan", "glutensiz", "sporcu"],
    variants: [
      {
        id: "badem-balli-250",
        name: "250g",
        weight: 250,
        price: 259,
        stock: 40,
        sku: "EZM-AB-250",
      },
      {
        id: "badem-balli-450",
        name: "450g",
        weight: 450,
        price: 469,
        stock: 28,
        sku: "EZM-AB-450",
      },
      {
        id: "badem-balli-850",
        name: "850g",
        weight: 850,
        price: 699,
        stock: 15,
        sku: "EZM-AB-850",
      },
    ],
    nutritionalInfo: { calories: 570, protein: 19, carbs: 24, fat: 48, fiber: 9, sugar: 10 },
    vegan: true,
    glutenFree: true,
    sugarFree: false,
    highProtein: true,
    rating: 5,
    reviewCount: 73,
    featured: false,
    new: false,
  },
  {
    id: "badem-klasik",
    name: "Klasik Badem Ezmesi",
    slug: "klasik-badem-ezmesi",
    description:
      "Klasik badem ezmesi. Tuzsuz, şeker ilavesiz, sadece badem. Doğal tatlılığı ile.",
    shortDescription: "Klasik usul badem ezmesi. Tuzsuz ve şekersiz.",
    category: "badem",
    subcategory: "klasik",
    images: ["/images/products/klasik-badem-1.jpg", "/images/products/klasik-badem-2.jpg"],
    tags: ["klasik", "vegan", "glutensiz", "keto"],
    variants: [
      {
        id: "badem-klasik-250",
        name: "250g",
        weight: 250,
        price: 259,
        stock: 48,
        sku: "EZM-AKLS-250",
      },
      {
        id: "badem-klasik-450",
        name: "450g",
        weight: 450,
        price: 469,
        stock: 35,
        sku: "EZM-AKLS-450",
      },
      {
        id: "badem-klasik-850",
        name: "850g",
        weight: 850,
        price: 699,
        stock: 20,
        sku: "EZM-AKLS-850",
      },
    ],
    nutritionalInfo: { calories: 620, protein: 20, carbs: 14, fat: 54, fiber: 10, sugar: 4 },
    vegan: true,
    glutenFree: true,
    sugarFree: true,
    highProtein: true,
    rating: 5,
    reviewCount: 91,
    featured: true,
    new: false,
  },

  // Ceviz Ezmeleri
  {
    id: "ceviz-sekersiz",
    name: "Şekersiz Ceviz Ezmesi",
    slug: "sekersiz-ceviz-ezmesi",
    description:
      "Yağ cevizinden üretilen, katkısız ve şekersiz ceviz ezmesi. Omega-3 kaynağı.",
    shortDescription:
      "İçeriğinde sadece ceviz bulunan %100 doğal ceviz ezmesi. Omega-3 zengini.",
    category: "ceviz",
    subcategory: "sekersiz",
    images: ["/images/products/sekersiz-ceviz-1.jpg", "/images/products/sekersiz-ceviz-2.jpg"],
    tags: ["doğal", "sekersiz", "vegan", "glutensiz", "omega3"],
    variants: [
      {
        id: "ceviz-sekersiz-250",
        name: "250g",
        weight: 250,
        price: 249,
        stock: 38,
        sku: "EZM-WIS-250",
      },
      {
        id: "ceviz-sekersiz-450",
        name: "450g",
        weight: 450,
        price: 449,
        stock: 25,
        sku: "EZM-WIS-450",
      },
      {
        id: "ceviz-sekersiz-850",
        name: "850g",
        weight: 850,
        price: 689,
        stock: 14,
        sku: "EZM-WIS-850",
      },
    ],
    nutritionalInfo: { calories: 650, protein: 15, carbs: 10, fat: 62, fiber: 5 },
    vegan: true,
    glutenFree: true,
    sugarFree: true,
    highProtein: false,
    rating: 5,
    reviewCount: 21,
    featured: true,
    new: false,
  },
  {
    id: "ceviz-balli",
    name: "Ballı Ceviz Ezmesi",
    slug: "balli-ceviz-ezmesi",
    description:
      "Ceviz ezmesi ile doğal arı balının birleşimi. Enerji ve besin değeri yüksek doğal besin.",
    shortDescription:
      "Ceviz ezmesine doğal arı balı eklenerek hazırlanmış enerji kaynağı.",
    category: "ceviz",
    subcategory: "balli",
    images: ["/images/products/balli-ceviz-1.jpg", "/images/products/balli-ceviz-2.jpg"],
    tags: ["doğal", "balli", "vegan", "glutensiz", "omega3"],
    variants: [
      {
        id: "ceviz-balli-250",
        name: "250g",
        weight: 250,
        price: 259,
        stock: 35,
        sku: "EZM-WIB-250",
      },
      {
        id: "ceviz-balli-450",
        name: "450g",
        weight: 450,
        price: 469,
        stock: 22,
        sku: "EZM-WIB-450",
      },
      {
        id: "ceviz-balli-850",
        name: "850g",
        weight: 850,
        price: 709,
        stock: 12,
        sku: "EZM-WIB-850",
      },
    ],
    nutritionalInfo: { calories: 610, protein: 14, carbs: 20, fat: 56, fiber: 4, sugar: 10 },
    vegan: true,
    glutenFree: true,
    sugarFree: false,
    highProtein: false,
    rating: 5,
    reviewCount: 38,
    featured: false,
    new: false,
  },
  {
    id: "ceviz-klasik",
    name: "Klasik Ceviz Ezmesi",
    slug: "klasik-ceviz-ezmesi",
    description:
      "Klasik ceviz ezmesi. Tuzsuz, şeker ilavesiz, sadece ceviz. Omega-3 deposu.",
    shortDescription: "Klasik usul ceviz ezmesi. Tuzsuz ve şekersiz.",
    category: "ceviz",
    subcategory: "klasik",
    images: ["/images/products/klasik-ceviz-1.jpg", "/images/products/klasik-ceviz-2.jpg"],
    tags: ["klasik", "vegan", "glutensiz", "omega3"],
    variants: [
      {
        id: "ceviz-klasik-250",
        name: "250g",
        weight: 250,
        price: 239,
        stock: 42,
        sku: "EZM-WIKLS-250",
      },
      {
        id: "ceviz-klasik-450",
        name: "450g",
        weight: 450,
        price: 429,
        stock: 30,
        sku: "EZM-WIKLS-450",
      },
      {
        id: "ceviz-klasik-850",
        name: "850g",
        weight: 850,
        price: 659,
        stock: 16,
        sku: "EZM-WIKLS-850",
      },
    ],
    nutritionalInfo: { calories: 660, protein: 14, carbs: 10, fat: 64, fiber: 5, sugar: 2 },
    vegan: true,
    glutenFree: true,
    sugarFree: true,
    highProtein: false,
    rating: 5,
    reviewCount: 45,
    featured: false,
    new: false,
  },

  // Kaju Ezmeleri
  {
    id: "kaju-sekersiz",
    name: "Şekersiz Kaju Ezmesi",
    slug: "sekersiz-kaju-ezmesi",
    description:
      "Hindistan cevizinden üretilen, katkısız ve şekersiz kaju ezmesi. Tatlı ve kremsi kıvamlı.",
    shortDescription:
      "İçeriğinde sadece kaju fıstığı bulunan %100 doğal kaju ezmesi.",
    category: "kaju",
    subcategory: "sekersiz",
    images: ["/images/products/sekersiz-kaju-1.jpg", "/images/products/sekersiz-kaju-2.jpg"],
    tags: ["doğal", "sekersiz", "vegan", "glutensiz"],
    variants: [
      {
        id: "kaju-sekersiz-250",
        name: "250g",
        weight: 250,
        price: 259,
        stock: 40,
        sku: "EZM-CJS-250",
      },
      {
        id: "kaju-sekersiz-450",
        name: "450g",
        weight: 450,
        price: 469,
        stock: 28,
        sku: "EZM-CJS-450",
      },
      {
        id: "kaju-sekersiz-850",
        name: "850g",
        weight: 850,
        price: 689,
        stock: 15,
        sku: "EZM-CJS-850",
      },
    ],
    nutritionalInfo: { calories: 590, protein: 18, carbs: 18, fat: 48, fiber: 4 },
    vegan: true,
    glutenFree: true,
    sugarFree: true,
    highProtein: false,
    rating: 5,
    reviewCount: 67,
    featured: false,
    new: false,
  },
  {
    id: "kaju-balli",
    name: "Ballı Kaju Ezmesi",
    slug: "balli-kaju-ezmesi",
    description:
      "Kaju ezmesi ile doğal arı balının birleşimi. Tatlı ve kremsi, eşsiz bir lezzet.",
    shortDescription:
      "Kaju ezmesine doğal arı balı eklenerek hazırlanmış tatlı lezzet.",
    category: "kaju",
    subcategory: "balli",
    images: ["/images/products/balli-kaju-1.jpg", "/images/products/balli-kaju-2.jpg"],
    tags: ["doğal", "balli", "vegan", "glutensiz"],
    variants: [
      {
        id: "kaju-balli-250",
        name: "250g",
        weight: 250,
        price: 269,
        stock: 35,
        sku: "EZM-CJB-250",
      },
      {
        id: "kaju-balli-450",
        name: "450g",
        weight: 450,
        price: 479,
        stock: 25,
        sku: "EZM-CJB-450",
      },
      {
        id: "kaju-balli-850",
        name: "850g",
        weight: 850,
        price: 719,
        stock: 12,
        sku: "EZM-CJB-850",
      },
    ],
    nutritionalInfo: { calories: 560, protein: 16, carbs: 26, fat: 44, fiber: 4, sugar: 12 },
    vegan: true,
    glutenFree: true,
    sugarFree: false,
    highProtein: false,
    rating: 5,
    reviewCount: 54,
    featured: false,
    new: false,
  },
  {
    id: "kaju-klasik",
    name: "Klasik Kaju Ezmesi",
    slug: "klasik-kaju-ezmesi",
    description:
      "Klasik kaju ezmesi. Tuzsuz, şeker ilavesiz, sadece kaju. Tatlı ve kremsi.",
    shortDescription: "Klasik usul kaju ezmesi. Tuzsuz ve şekersiz.",
    category: "kaju",
    subcategory: "klasik",
    images: ["/images/products/klasik-kaju-1.jpg", "/images/products/klasik-kaju-2.jpg"],
    tags: ["klasik", "vegan", "glutensiz"],
    variants: [
      {
        id: "kaju-klasik-250",
        name: "250g",
        weight: 250,
        price: 259,
        stock: 45,
        sku: "EZM-CJKLS-250",
      },
      {
        id: "kaju-klasik-450",
        name: "450g",
        weight: 450,
        price: 469,
        stock: 32,
        sku: "EZM-CJKLS-450",
      },
      {
        id: "kaju-klasik-850",
        name: "850g",
        weight: 850,
        price: 689,
        stock: 18,
        sku: "EZM-CJKLS-850",
      },
    ],
    nutritionalInfo: { calories: 600, protein: 17, carbs: 17, fat: 50, fiber: 4, sugar: 3 },
    vegan: true,
    glutenFree: true,
    sugarFree: true,
    highProtein: false,
    rating: 5,
    reviewCount: 101,
    featured: true,
    new: false,
  },

  // Paketler
  {
    id: "paket-super-ikili",
    name: "Ballı Badem & Klasik Badem Paketi",
    slug: "balli-badem-klasik-badem-paketi",
    description:
      "İki favori badem ezmesi bir arada. Ballı badem ezmesi ve klasik badem ezmesi 450'şer gram.",
    shortDescription:
      "Ballı badem ezmesi ve klasik badem ezmesi 450'şer gram. Toplam 900g.",
    category: "paketler",
    subcategory: "klasik",
    images: ["/images/products/paket-super-ikili-1.jpg"],
    tags: ["paket", "badem", "hediye"],
    variants: [
      {
        id: "paket-super-ikili",
        name: "900g (2x450g)",
        weight: 900,
        price: 519,
        stock: 20,
        sku: "EZM-PKT-SI",
      },
    ],
    nutritionalInfo: { calories: 590, protein: 20, carbs: 16, fat: 52, fiber: 9, sugar: 7 },
    vegan: true,
    glutenFree: true,
    sugarFree: false,
    highProtein: true,
    rating: 5,
    reviewCount: 0,
    featured: true,
    new: true,
  },
  {
    id: "paket-gunluk-kahvalti",
    name: "Ezmeo Günlük Kahvaltı Paketi",
    slug: "ezmeo-gunluk-kahvalti-paketi",
    description:
      "Her gün farklı bir lezzet. 4 çeşit ezme 250'şer gram. Fındık, fıstık, badem ve ceviz.",
    shortDescription:
      "4 çeşit ezme 250'şer gram. Fındık, fıstık, badem ve ceviz. Toplam 1000g.",
    category: "paketler",
    subcategory: "klasik",
    images: ["/images/products/paket-kahvalti-1.jpg"],
    tags: ["paket", "kahvalti", "hediye", "cesitli"],
    variants: [
      {
        id: "paket-kahvalti",
        name: "1000g (4x250g)",
        weight: 1000,
        price: 599,
        stock: 15,
        sku: "EZM-PKT-KAH",
      },
    ],
    nutritionalInfo: { calories: 600, protein: 18, carbs: 14, fat: 54, fiber: 7, sugar: 6 },
    vegan: true,
    glutenFree: true,
    sugarFree: true,
    highProtein: true,
    rating: 5,
    reviewCount: 0,
    featured: true,
    new: true,
  },
];

// Yardımcı Fonksiyonlar
export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

export function getFeaturedProducts(limit = 8): Product[] {
  return PRODUCTS.filter((p) => p.featured).slice(0, limit);
}

export function getNewProducts(limit = 4): Product[] {
  return PRODUCTS.filter((p) => p.new).slice(0, limit);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return PRODUCTS.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some((t) => t.toLowerCase().includes(q))
  );
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return PRODUCTS.filter(
    (p) => p.category === product.category && p.id !== product.id
  ).slice(0, limit);
}
